### ISSUE TITLE
Retire byte[]-based API in favour of Stream-based one

### ISSUE THREAD

**Issue by anton-gogolev** [kotofsky/DocMaker#1]
Specifically, `WordBuilder.Build()` should be returning a `Stream` instance.

**Comment by kotofsky** [comment]
if this ok, i push it to master. https://github.com/kotofsky/DocMaker/tree/stream-based

**Comment by anton-gogolev** [comment]
Nope. 

Your Build() function should be returning Stream, not MemoryStream. What’s worse, you are disposing of a templateStream in the GenerateStream() method.

Where are your tests, dude 😉 ?

**Comment by anton-gogolev** [comment]
Oh, nevermind. `DocumentFormat.OpenXml` does not properly work with Streams.
